exclude: ^(translations/|.*\.css|.*\.svg|YOUR_PLUGIN_PACKAGE/_version.py|versioneer.py|.vscode/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: fix-encoding-pragma
  - repo: https://github.com/OctoPrint/codemods
    rev: 0.5.0
    hooks:
      - id: codemod_dict_to_literal
        stages: ["manual"]
      - id: codemod_set_to_literal
        stages: ["manual"]
      - id: codemod_not_in
        stages: ["manual"]
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.8.0
  #   hooks:
  #     - id: isort
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
